version: '3.8'

services:
  postgres:
    container_name: focus-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: